### ISSUE TITLE
Error from server (BadRequest): a container name must be specified for pod csi-provisioner-attacher-0, choose one of: [csi-provisioner csi-attacher]

### ISSUE THREAD

**Issue by zhangyin26825** [AliyunContainerService/csi-plugin#12]
按照git上的文档安装了下，csi-provisioner-attacher 启动不起来，查看日志  提示

Error from server (BadRequest): a container name must be specified for pod csi-provisioner-attacher-0, choose one of: [csi-provisioner csi-attacher]

用  describe 命令 提示
  Warning  FailedScheduling  3m (x1261 over 1h)  default-scheduler  0/3 nodes are available: 3 node(s) didn't match node selector.

修改了 storageclass.yaml 里的  
   zoneId: cn-shenzhen-a
    regionId: cn-shenzhen
阿里云服务器属于 华南

**Comment by fredkan** [comment]
Warning FailedScheduling 3m (x1261 over 1h) default-scheduler 0/3 nodes are available: 3 node(s) didn't match node selector.

你加了nodeSelector，没有节点符合条件。

**Comment by zhangyin26825** [comment]
你好，那我需要修改 哪个配置文件的 哪些地方

**Comment by zhangyin26825** [comment]
正常情况下  disk-provisioner-attacher.yaml   这个文件，我需不需要修改

**Comment by fredkan** [comment]
disk-provisioner-attacher 是默认安装到master的，需要master节点上有下面的label。
      nodeSelector:
         node-role.kubernetes.io/master: ""

你可以去掉这个nodeSelector进行部署。

**Comment by fredkan** [comment]
> 我在master 加上 node-role.kubernetes.io/master: "" 这个 label
> 提示
> Warning FailedScheduling 1m (x839 over 48m) default-scheduler 0/3 nodes are available: 1 node(s) had taints that the pod didn't tolerate, 2 node(s) didn't match node selector.
> 然后我给 另外一个node节点也加上 同样的 label
> 
> csi-provisioner-attacher 已经正常运行了，
> 
> 当 运行完 # kubectl create -f ./deploy/disk/deploy.yaml
> 
> # kubectl get pvc
> NAME STATUS VOLUME CAPACITY ACCESS MODES STORAGECLASS AGE
> disk-pvc Pending
> #kubectl get pv
> No resources found.
> 跟文档上显示的结果不一样，
> 这中间 我唯一修改的文件是 storageclass.yaml 里
> zoneId: cn-shenzhen-a
> regionId: cn-shenzhen
> 是不是 我的值填错了，我该怎么获取 zoneId 跟 regionId

还有问题吗？Disk最近做了一些更新，你可以使用新版本测试一下。
