### ISSUE TITLE
pvc created pending

### ISSUE THREAD

**Issue by mofei920** [AliyunContainerService/csi-plugin#14]
张家口阿里云服务器a区自建k8，版本1.12.3，3个master,  2个woker节点。
disk-plugin.yaml 文件已设置AK，但是创建pvc时显示pending.
另外高效云盘已格式化挂载到了master01上，是不是哪里需要指定volumnid？磁盘需要手动格式化吗？
多谢解答。

<pre>
storageclass 设置如下：
# cat storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-disk
provisioner: csi-diskplugin
parameters:
    zoneId: cn-zhangjiakou-a
    regionId: cn-zhangjiakou
    fsType: ext4
    type: cloud_efficiency
    readOnly: "false"
reclaimPolicy: Delete

csi pod已成功运行：
# kubectl get pod | grep -E 'csi|NAME'
NAME                                      READY   STATUS    RESTARTS   AGE
csi-diskplugin-47wtn                      2/2     Running   0          7h1m
csi-diskplugin-7wdvq                      2/2     Running   0          7h1m
csi-diskplugin-pl4qz                      2/2     Running   0          7h1m
csi-diskplugin-sn4cx                      2/2     Running   0          7h1m
csi-diskplugin-ztgfg                      2/2     Running   0          7h1m
csi-provisioner-attacher-0                2/2     Running   1          7h37m

pvc 状态为Pending：
# kubectl get sc,pv,pvc
NAME                                   PROVISIONER      AGE
storageclass.storage.k8s.io/csi-disk   csi-diskplugin   7h1m

NAME                             STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/disk-pvc   Pending                                      csi-disk       6h41m

pvc 没有错误日志：
# kubectl describe persistentvolumeclaim/disk-pvc
Name:          disk-pvc
Namespace:     default
StorageClass:  csi-disk
Status:        Pending
Volume:
Labels:        <none>
Annotations:   control-plane.alpha.kubernetes.io/leader:
                 {"holderIdentity":"1b834f9a-2d87-11e9-ad9e-0a58c0a80006","leaseDurationSeconds":15,"acquireTime":"2019-02-10T23:52:08Z","renewTime":"2019-...
               volume.beta.kubernetes.io/storage-provisioner: csi-diskplugin
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
Events:
  Type       Reason                Age                       From                         Message
  ----       ------                ----                      ----                         -------
  Normal     ExternalProvisioning  2m10s (x2685 over 6h47m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "csi-diskplugin" or manually created by system administrator
Mounted By:  <none>
</pre>

**Comment by fredkan** [comment]
pvc为pending，那应该是provisioner没有创建pv。看一下disk-plugin的日志。

**Comment by fredkan** [comment]
Disk Plugin is updated, and will add more features in 1.0.0 version. Try with latest version again.
