### ISSUE TITLE
Incorrectly named drivers

### ISSUE THREAD

**Issue by saad-ali** [AliyunContainerService/csi-plugin#16]
Per the [CSI spec](https://github.com/container-storage-interface/spec/blob/master/spec.md#getplugininfo) the name of a CSI driver must conform to the following requirements:

```
The name MUST follow domain name notation format (https://tools.ietf.org/html/rfc1035#section-2.3.1).

It SHOULD include the plugin's host company name and the plugin name, to minimize the possibility of collisions.

It MUST be 63 characters or less, beginning and ending with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), dots (.), and alphanumerics between.

This field is REQUIRED.
```

The current names are:
* csi-diskplugin
* csi-nasplugin
* csi-ossplugin

Consider renaming to include the fully qualified domain name, maybe something like:
* diskplugin.csi.alibabacloud.com
* nasplugin.csi.alibabacloud.com
* ossplugin.csi.alibabacloud.com

To be clear the sepc says `SHOULD include the plugin's host company name and the plugin name` so this is not a requirement. But considering how generic these names are I strongly recommend it to prevent collisions with other CSI Drivers.

**Comment by fredkan** [comment]
> Per the [CSI spec](https://github.com/container-storage-interface/spec/blob/master/spec.md#getplugininfo) the name of a CSI driver must conform to the following requirements:
> 
> ```
> The name MUST follow domain name notation format (https://tools.ietf.org/html/rfc1035#section-2.3.1).
> 
> It SHOULD include the plugin's host company name and the plugin name, to minimize the possibility of collisions.
> 
> It MUST be 63 characters or less, beginning and ending with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), dots (.), and alphanumerics between.
> 
> This field is REQUIRED.
> ```
> The current names are:
> 
> * csi-diskplugin
> * csi-nasplugin
> * csi-ossplugin
> 
> Consider renaming to include the fully qualified domain name, maybe something like:
> 
> * diskplugin.csi.alibabacloud.com
> * nasplugin.csi.alibabacloud.com
> * ossplugin.csi.alibabacloud.com
> 
> To be clear the sepc says `SHOULD include the plugin's host company name and the plugin name` so this is not a requirement. But considering how generic these names are I strongly recommend it to prevent collisions with other CSI Drivers.

Great proposal, I will consider to update that.
Thank you very much @saad-ali

**Comment by fredkan** [comment]
named to *.csi.alibabacloud.com
```
        TYPE_PLUGIN_DISK = "diskplugin.csi.alibabacloud.com"
	TYPE_PLUGIN_NAS  = "nasplugin.csi.alibabacloud.com"
	TYPE_PLUGIN_OSS  = "ossplugin.csi.alibabacloud.com"
```
Thanks @saad-ali
