### ISSUE TITLE
driver name csi-ossplugin not found in the list of registered CSI drivers

### ISSUE THREAD

**Issue by tommenx** [AliyunContainerService/csi-plugin#17]
I have deploy the CSI plugin in my local kubernetes V1.13, and enable FeatureGate about CSI in kubelet and api-server,  and I have set my AK account and secret and bucket name in ./deploy/oss/deploy.yaml
when describe pod nginx it says driver name not found in the list of registered CSI drivers as the picture says blow
<img width="1867" alt="2019-02-22 2 13 23" src="https://user-images.githubusercontent.com/32902235/53223361-0d7bc200-36ac-11e9-9061-e108e1488903.png">
can you help me fix it ? 
thank you

**Comment by fredkan** [comment]
> I have deploy the CSI plugin in my local kubernetes V1.13, and enable FeatureGate about CSI in kubelet and api-server, and I have set my AK account and secret and bucket name in ./deploy/oss/deploy.yaml
> when describe pod nginx it says driver name not found in the list of registered CSI drivers as the picture says blow
> <img alt="2019-02-22 2 13 23" width="1867" src="https://user-images.githubusercontent.com/32902235/53223361-0d7bc200-36ac-11e9-9061-e108e1488903.png">
> can you help me fix it ?
> thank you

OK, can you provide more logs from the /var/log/message. From the node of issue pod.

**Comment by tommenx** [comment]
[root@localhost ~]# cat /var/log/alicloud/csi-ossplugin.log
```
time="2019-02-22T05:51:06Z" level=info msg="CSI Driver: %!(EXTRA string=csi-ossplugin, string=localhost.localdomain, string=unix://var/lib/kubelet/plugins/csi-ossplugin/csi.sock)"
time="2019-02-22T05:51:06Z" level=info msg="Driver: csi-ossplugin version: 0.2.0"
```

**Comment by fredkan** [comment]
@tommenx I update the oss plugin, please try again.
[https://github.com/AliyunContainerService/csi-plugin/blob/master/docs/README-oss.md](url)

**Comment by tommenx** [comment]
I have tried this, and there is still something wrong with the oss-plugin deploy file, and I have make some change with them. it works in my local kubernetes cluster。

**Comment by fredkan** [comment]
> �I have tried this, and there is still something wrong with the oss-plugin deploy file, and I have make some change with them. it works in my local kubernetes cluster。

Thanks the update. I have try your update, it is good idea to reduce one oss-plugin container.
I will merge the PR. Thank you very much.
