### ISSUE TITLE
oss Pod get "transport endpoint is not connected" when restart ossplugin

### ISSUE THREAD

**Issue by fredkan** [AliyunContainerService/csi-plugin#22]
One pod is using OSS volume.
The mountpoint will get "transport endpoint is not connected" error, if restart the ossplugin.

The reason is oss volume use fuse to connect with server, which is in user space. Restart ossplugin will kill all process belongs to the pod.

Using "systemd-run --scope -- " is also useless. 

Issues is tracking this:
https://github.com/kubernetes/kubernetes/issues/70013
https://github.com/kubernetes/kubernetes/issues/7890

**Comment by fredkan** [comment]
resolve this issue with workaround:
https://github.com/AliyunContainerService/csi-plugin/blob/master/docs/oss-upgrade.md

**Comment by zemul** [comment]
> resolve this issue with workaround: https://github.com/AliyunContainerService/csi-plugin/blob/master/docs/oss-upgrade.md

使用如上解决方案，但是我的mount挂载kill并重新挂载挂载以后，无法传播到pod中去，请问有什么解决方案吗？
