### ISSUE TITLE
csi-plugin's logs are emitted to local file

### ISSUE THREAD

**Issue by jia-jerry** [AliyunContainerService/csi-plugin#5]
As csi-plugin is a cloud native app, it is better for it to emit logs to stdout.
Need command arguments to let the plugin log to stdout instead of file.

**Comment by fredkan** [comment]
Yes, but when the pod removed, log also lost. 

CSI-Plugin is a daemonset, the log is stable for the location. So I use the volume for saving.

It is better to output both.

**Comment by jia-jerry** [comment]
Not both. Just let users to choose either of them. For me, I would like to choose stdout only :)

I just regard it as normal apps, which are suggested to emit logs to stdout. We use third party tools like fluentd to scribe the container logs which by default exists in /var/log/containers  fold on every k8s nodes

**Comment by denverdino** [comment]
@fredkan , I am with @jia-jerry 
Can you revisit the logging impl? thx

**Comment by fredkan** [comment]
@jia-jerry thanks for your suggestion, code is updated, pls try it.

https://github.com/AliyunContainerService/csi-plugin/blob/master/deploy/disk/diskplugin.yaml

**Comment by jia-jerry** [comment]
Thanks, Fred Kan.
