### ISSUE TITLE
Build时报错

### ISSUE THREAD

**Issue by wclw** [AliyunContainerService/csi-plugin#50]
# pwd
/tmp/csi-plugin/build
# sh build-disk.sh
main.go:27:2: cannot find package "github.com/AliyunContainerService/csi-plugin/pkg/disk" in any of:
	/usr/local/go/src/github.com/AliyunContainerService/csi-plugin/pkg/disk (from $GOROOT)
	/root/go/src/github.com/AliyunContainerService/csi-plugin/pkg/disk (from $GOPATH)
main.go:28:2: cannot find package "github.com/AliyunContainerService/csi-plugin/pkg/lvm" in any of:
	/usr/local/go/src/github.com/AliyunContainerService/csi-plugin/pkg/lvm (from $GOROOT)
	/root/go/src/github.com/AliyunContainerService/csi-plugin/pkg/lvm (from $GOPATH)
main.go:29:2: cannot find package "github.com/AliyunContainerService/csi-plugin/pkg/nas" in any of:
	/usr/local/go/src/github.com/AliyunContainerService/csi-plugin/pkg/nas (from $GOROOT)
	/root/go/src/github.com/AliyunContainerService/csi-plugin/pkg/nas (from $GOPATH)
main.go:30:2: cannot find package "github.com/AliyunContainerService/csi-plugin/pkg/oss" in any of:
	/usr/local/go/src/github.com/AliyunContainerService/csi-plugin/pkg/oss (from $GOROOT)
	/root/go/src/github.com/AliyunContainerService/csi-plugin/pkg/oss (from $GOPATH)
main.go:31:2: cannot find package "github.com/Sirupsen/logrus" in any of:
	/usr/local/go/src/github.com/Sirupsen/logrus (from $GOROOT)
	/root/go/src/github.com/Sirupsen/logrus (from $GOPATH)

**Comment by fredkan** [comment]
1. update the source code;
2. config GOPATH, GOROOT
