### ISSUE TITLE
Not compatible with Kubernetes 1.12 yet

### ISSUE THREAD

**Issue by zerda** [AliyunContainerService/csi-plugin#6]
Kubernetes 1.12 introduced some breaking changes, it makes current release (v0.2.0) is not working at all.

From PR [Add CSI action required to 1.12 release notes](https://github.com/kubernetes/kubernetes/pull/69903)
* In anticipation of CSI 1.0 in the next release, Kubernetes 1.12 calls the CSI `NodeGetInfo` RPC instead of `NodeGetId` RPC. Ensure your CSI Driver implements `NodeGetInfo(...)` before upgrading to 1.12. [@saad-ali](https://github.com/kubernetes/kubernetes/issues/68688)
* Kubernetes 1.12 also enables [Kubelet device plugin registration](https://github.com/kubernetes/features/issues/595) feature by default. Before upgrading to 1.12, ensure the `driver-registrar` CSI sidecar container for your CSI driver is configured to handle plugin registration (set the `--kubelet-registration-path` parameter on `driver-registrar` to expose a new unix domain socket to handle Kubelet Plugin Registration).

Any and all help is much appreciated.

**Comment by fredkan** [comment]
CSI is in 0.4.0 now, and changes frequently. Snapshot, Resize and many interfaces will be added in following release.

1.12 support and CSI version updating will be focused, we will upgrade the plugin recently.

**Comment by bittopaz** [comment]
Any progress on this, please? @fredkan

**Comment by fredkan** [comment]
0.3.0 works for 1.12
1.0.0 works for 1.13

**Comment by bittopaz** [comment]
thanks @fredkan

**Comment by fredkan** [comment]
csiplugin will focus on v1.0.0, close this issue.
